
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				chicken = true
				panda = true
				villager = true
				skeleton_horse = true
				wandering_trader = true
				zombie_villager = true
				cow = true
				pig = true
				horse = true
				skeleton = true
				bat = true
				zombified_piglin = true
				zombie = true
				mooshroom = true
				witch = true
				armor_stand = true
				glow_squid = true
				spider = true
				creeper = true
				sheep = true
				player = true
				enderman = true
				experience_orb = true
				rabbit = true
				slime = true
				lightning_bolt = true
				drowned = true
				bee = true
				axolotl = true
				shulker = true
				stray = true
				area_effect_cloud = true
				husk = true
				phantom = true
				blaze = true
				wither_skeleton = true
				potion = true
				cat = true
				iron_golem = true
				wolf = true
				painting = true
				leash_knot = true
				boat = true
				cod = true
				salmon = true
				goat = true
				sniffer = true
				allay = true
				squid = true
				donkey = true
				vindicator = true
				pillager = true
				arrow = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.buzzier_bees]
				moobloom = true

			[light_sources.settings.entities.wildernature]
				squirrel = true
				minisheep = true
				flamingo = true
				bison = true
				boar = true
				penguin = true
				hedgehog = true
				raccoon = true
				deer = true
				cassowary = true
				pelican = true
				red_wolf = true
				owl = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.botania]
				mana_burst = true

			[light_sources.settings.entities.atmospheric]
				cochineal = true

			[light_sources.settings.entities.furniture]
				pells = true

			[light_sources.settings.entities.species]
				deflector_dummy = true
				limpet = true
				deepfish = true
				goober = true
				bewereager = true
				wicked = true
				ghoul = true
				birt = true
				mammutilation = true
				springling = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.untitledduckmod]
				duck = true
				goose = true

			[light_sources.settings.entities.quark]
				shiba = true
				forgotten = true
				toretoise = true
				stoneling = true

			[light_sources.settings.entities.longwings]
				moth = true
				butterfly = true

			[light_sources.settings.entities.farmlife]
				galliraptor = true
				domestic_tribull = true
				galliraptor_egg = true

			[light_sources.settings.entities.autumnity]
				turkey = true
				snail = true

			[light_sources.settings.entities.meadow]
				wooly_sheep = true
				wooly_cow = true
				water_buffalo = true

			[light_sources.settings.entities.snowpig]
				snow_pig = true

			[light_sources.settings.entities.hamsters]
				hamster = true

			[light_sources.settings.entities.splendid_slimes]
				splendid_slime = true

			[light_sources.settings.entities.unusualfishmod]
				deep_crawler = true
				shockcat = true
				prawn = true
				blindsailfin = true
				sea_spider = true
				triple_twirl_pleco = true
				hatchet_fish = true

			[light_sources.settings.entities.crittersandcompanions]
				leaf_insect = true
				otter = true
				koi_fish = true
				shima_enaga = true
				ferret = true

			[light_sources.settings.entities.windswept]
				chilled = true
				frost_arrow = true
				frostbiter = true

			[light_sources.settings.entities.balloonbox]
				balloonbox = true

			[light_sources.settings.entities.apexcore]
				seat = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.legendarycreatures]
				forest_mojo = true
				desert_mojo = true
				ender_wisp = true
				nether_wisp = true

			[light_sources.settings.entities.trials]
				breeze = true

			[light_sources.settings.entities.rottencreatures]
				zap = true
				undead_miner = true
				frostbitten = true
				hunter_wolf = true
				glacial_hunter = true
				immortal = true
				mummy = true
				burned = true

			[light_sources.settings.entities.champions]
				arctic_bullet = true
				enkindling_bullet = true

			[light_sources.settings.entities.strawstatues]
				straw_statue = true

			[light_sources.settings.entities.crabbersdelight]
				crab = true

			[light_sources.settings.entities.smallships]
				brigg = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.liltractor]
				liltractor = true

			[light_sources.settings.entities.blueprint]
				boat = true

			[light_sources.settings.entities.simplehats]
				hatdisplay = true

			[light_sources.settings.entities.supplementaries]
				hat_stand = true

			[light_sources.settings.entities.bakery]
				wandering_baker = true

			[light_sources.settings.entities.etcetera]
				chapple = true

			[light_sources.settings.entities.vinery]
				wandering_winemaker = true
				mule = true

			[light_sources.settings.entities.aquaculture]
				starshell_turtle = true

			[light_sources.settings.entities.relics]
				life_essence = true

